name: Build & Test CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: npm i
            - name: Build packages
              run: npm run build
            - name: Automated tests
              run: npm run test
         